version: '3.1'
services:
  discovery-service:
    image: betulcetinkaya/discovery-service:${TAG}
    container_name: discovery-service
    ports:
      - 8761:8761
    networks:
        - services
networks:
  services:
    external:
      name: services
